---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gobin
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gobin-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: gobin
