---
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  features:
    logCollection:
      enabled: true
      containerCollectAll: true
    # liveContainerCollection:
    #   enabled: true
    # orchestratorExplorer:
    #   enabled: false
    # processAgent:
    #   enabled: true
    #   processCollection: true
  global:
    clusterName: home-ops
    site: datadoghq.com
