# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:AaIejZjQ8rf4qJ132u4pALL9NemXd648hH7krH+jZwpiVAORF6mXG3C99NQaZW7HSuMEgbyLMa/sIQ7oU2XVUdtD1FJ6CkWvFTITclwOUBz8V2zXg6UGsPfdG3W1wFmo5q5mMJomgtMr8tOpBjLuQ1gpaHqN67O7X3uww9ssuXCy1C0Wz4lmCF8ossyv2xYXIypBSGRpdKDDjkf5h9dTo1o/xmwpTqIPSJTgHHBmOM1zlY7nAQ==,iv:SVFC5nmxbPfTtZrGvCmwExCSnTilANPouS8NXe2CSog=,tag:gJO2F3SlqQjznmAIo/b+GQ==,type:str]
sops:
  age:
    - recipient: age18p353vdvr8n8rlm7xn24qpff5r7c8s0688jyw7hlcxg04r9aq5lqlz0qm2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQkxXS3JRVnkvckYxRE1x
        VUVuVldHRnZsa0QxRHZGSk1WdWFmTUdpV0I4Ckp6dWkyZTM5aEgraXR5SjdGSzRI
        dGlxeWJEcUk4bnhwb1gvV0ljYXFSTVEKLS0tICthYWwyaWllSkdGNk9BQ0dONVFm
        NXNIWVVubmFVZ2NiVndyM0N0YVg3cmMKgIx2qlbOFQKmPldqN3k6eQpmpppUkf4a
        ZKHEVGkGXvcXIyNuHDYRSfB1syfwLKkXSJVEYM8BR5GIlbUOyQluvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-09T16:44:53Z"
  mac: ENC[AES256_GCM,data:9sLKfqXP2MpP/j+UwXS1MltF6YkgOcvO1sYSDgsb7qoyDT2qlQM4xGl2g8j5b5H/LQnew6z999HPCGHgvGOouvu4RHuZuevQ+PauynDozz0BMlsikHBg9vSNLQoFbTRiRB1UskJAPrtzCJ8wOd1+NMgHTDf35EffAYLj7zQwTCc=,iv:zrTUj7dkUBqx3LrBdnwvIRIGNh3CXwMbgB0CtzT/O+I=,tag:dHKBce21EM7+tnW6GJD52g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.1
