---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
commonAnnotations:
  "app.kubernetes.io/managed-by": "Helm"
  "meta.helm.sh/release-name": "datadog"
  "meta.helm.sh/release-namespace": "observability"
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
