apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Y/bBG7KRsNane2K2CgIg8c4QisoNAu4vgcrH5Ib/QZqnNMu4,iv:XYxmsZxVTiKlBOoBaZ3xuKwEeMcHQCZY//J6avVWSew=,tag:/eyLhENTir+r/3VIhQTxYQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:iAFyFk99CRurMsJCV7C8RFFvA2PezCrTvpkctCn5RQja4zQfs+ukklFalkC1Tv0FktCRtc+QgyMmAmArD/QVyeLL8L/Ttq86aIP1WLvHLWfBQwyDn9NzJwhR4SvN4I5p9Hrk1L3NaHPio4UXxDZHrZ6eRxWTiIC8kE3ytp3V85skm7xULNLq07F1NnvCXDXudLOm7gmVU3AhKpY71q0R3sVcd6svqgR6Xzi+JPDQQw==,iv:QBojIE1CDHlIHuhbBW5Qs52CbJSp73xyZETxNPvXR5s=,tag:9BdQA6ICTc8kDwVzWcCXZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSktML2NRZjFOb01KT0o1
            WGJHZHdLb3M2YWlwWjZNeTNZRnFNWW9KeUJvCmQ0c1h1Wmp5MmRLeXRaaTBjSG42
            ZlIySkE5Yk5KU1NyazFtOFNZUlc0ZEkKLS0tIEttNFNnTVNUcDNhczUydUpPZ3p4
            aWpRZXZtWkVPQkxOa3J4a1FJMGxyQUEKnwqLXHkdanmBQ3YN2vb1wIbCvCQ62Gnb
            drxDnsTyXF/rOs51Q5XIgKxCzGL5xv835tvN7OFOBYOiXiEyo8eIKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T16:19:48Z"
    mac: ENC[AES256_GCM,data:EY88511jY9YigMk7/XUSms1MIqMhMINFqatgsc+lhbukNhe7fGgiZyyXlKZ09XyPrkxqOPAwB6tej+t8kzehOkyJ9QS9RTPqEJWnH0qN8cWucGtRO6X3b7GESuLkpOBsy2kjgIYL9znBfwLssMBqqoUB168Q1OFES6EAFjwWfkA=,iv:+XSxuAEZlKBzZxwa/wkUKLbfqDTvvBNjOML6IJ/63nw=,tag:k0eL7Pzq7uCzF3J7PLRTgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
