apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:wsijOt/+BDcRyu4Ah8sIr3f92yeC5SHgvZutog9sf4oX4fL9,iv:tvy1EfgAjC94EqqSsgXgD6E6DczDlyv4m2CW6aSDFfU=,tag:hCnvEOFayxDFRucTqznR9A==,type:str]
    credentials.json: ENC[AES256_GCM,data:fnKWTD94j/+e6NMRaqCsSE18SWSgm+bO6rjE0Ljfdp3Q1Eo/nrrLIT4wxKuYKGdORsVuS7wx9H+1riaPGHNC4nHlGXtakRGO9vEWU+Lsl7E1GYwr+seBQWnL6KJALO/i8XqFEO7BgnThGP5VtsimHZyIL6EQYeN8O3tvUK9cfcbZhXBDJJjb7fPl2IJnkoYjwtd6YflbBoC2cx+dTbhLnEoG1ToD4R5PbasHlyMUsA==,iv:NDjdS+i+qfQPwamhAoa8sUYojU1Urd0jNQMTBlnOV7Q=,tag:mEu/Vb1SQgxPwxhA/raTeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWXovUGovTHBCK2xheHJu
            VnpDWHd0T0FlaGpaQXpWNTBEeldtdFdYNWpvCnQ5TjVHcS9qZHM1VVZnNFJjU1cv
            RitIV1BjUGM2aUZkbU5XNnJtcmp6K2sKLS0tICt4d0xTSUpiN0xxQ3M0SVVLRHRl
            T240dDEzbmxFeFFoaklWQ2w2K3BWZUkKQWmk33jaznsqIkh/zvZqwpp6a1Vl3xe4
            o5hEuxsL0p51ETcgHAP4BSMz2z4FXCGhyaVqPUOcPL3VzZ+nBhZLHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T15:43:40Z"
    mac: ENC[AES256_GCM,data:eoVhZwAc6Ec6IHWc04BkSCSsEXwUufWjqew+/qqwuEkyTnwKiBwpC9XP0aQ00OtvdLwnn0ph6kEZIYHFYTMuudOhds4NeYz93zo0rDehQ5CZARgpw3q5DqEwLQJwOqeKoT+GxIslaAVpyTfSxHfhGpRaNaNv4R0olsaqGYom8xY=,iv:iCr4JOMgEDMNprLmU6PuxMOEZfXWyHB1jEGO3ypv8wA=,tag:jz+uU/axofYxrCnTM5sDSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
