apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:WXrKaNrWSWDV6BBpjeJtbtbuhOK3q0SRhwgF0lYXv2GLaJJ5,iv:36GBRxwjzRBi7V+GI827bucvJ92gBcjSSMjv0j3HBbc=,tag:wQMfbVJmy5L3XQV89L6v0w==,type:str]
    credentials.json: ENC[AES256_GCM,data:vTIhrEPYwvskpdsAobyviwDw+oX7cCnT7F2KB41QN3cXQLOvLor4Pj23utREC83QjJ6HPXl/5qtGdQQLWIaBKIKFYQ6HAptNJDclcxtow6r8SXBPvNZH26pidcQB4A2+YWAgvIzyWmnHp+BBGRQd57hTlVBd9n6aX+YMZVCKdHIFhsgYmyntz0EhcZ6KGxC8Q8eI25Y5jWB6nwbpqoD/46nS/FsObUHnGziMH3cwGQ==,iv:GAtYvo+XtodtiaETsvGsopjATyPmKj2qt3Pr6e1Y94E=,tag:WyPQYhnVI1RC06JXKyOkAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtS1VvZXhNQWR4dCtjUFMv
            Q2xzRnVNUUxMQXNRQ0NjWXkzK3Y4WXBHN0RvCnU5L0dhSmlyeU9TTENjQm1Ib2RO
            dHdPNXJTc3RBeVF6R0VuVTFPYzljUWcKLS0tIDMwWktsUTVtT1VsdkNhb1hIOU00
            clFuSHc0MXppMGRrQnFrNU5SVnorYjgKTInvB4YJKcttoR+NdRc1q0OyXqWIIcyc
            hlfn4PFKwrfJcu4yQrWMFXdSUhBxqIdq0clV3eQd42ASH7vhVppAkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T18:52:27Z"
    mac: ENC[AES256_GCM,data:ML/N44WjTm0dyV3+HO8x09XtWyDFjV++yT1bgh1ebIbwE8WFe5wcFZAWkzvHhDDW5UsEJ4w+RyMTRaWKr1/xXloE0qKyojHZjoHMX90CZETkUu9jDYlwXrv+KCAa7Sn2bPKZin6hE4sNJoyTYPrgmkdLGNcEpkMhl1wGp+VGg+w=,iv:g1QmkJ4PgGEFmnyZ8BVtAJQbFwEN/GFONw6w2NqieFo=,tag:Kp3uuQljJNv0Ifod+9wuAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
