---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
  labels:
    recurring-job-group.longhorn.io/daily-backup: enabled
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
