---
kubernetes:
  children:
    controllers:
      hosts:
        "k8s-0":
          ansible_user: "phekno"
          ansible_host: "10.100.50.6"
        "k8s-1":
          ansible_user: "phekno"
          ansible_host: "10.100.50.5"
        "k8s-2":
          ansible_user: "phekno"
          ansible_host: "10.100.50.7"
