---
defaults:
  badge:
    style: flat

badges:
  - id: nodes
    title: nodes
    query: count(kube_node_info)
    valueExpr: string(result)
    colorExpr: '"blue"'
    icon: si:kubernetes

  - id: pods
    title: pods
    query: count(kube_pod_info)
    valueExpr: string(result)
    colorExpr: '"blue"'

  - id: cpu
    title: cpu
    query: >-
      round(sum(1 - rate(node_cpu_seconds_total{mode="idle"}[5m])) /
      count(node_cpu_seconds_total{mode="idle"}) * 100, 0.1)
    valueExpr: string(result) + "%"
    colorExpr: 'result < 60.0 ? "green" : (result < 85.0 ? "orange" : "red")'

  - id: memory
    title: memory
    query: >-
      round(sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) /
      sum(node_memory_MemTotal_bytes) * 100, 0.1)
    valueExpr: string(result) + "%"
    colorExpr: 'result < 70.0 ? "green" : (result < 90.0 ? "orange" : "red")'

  - id: age
    title: cluster age
    query: round((time() - min(kube_node_created)) / 86400)
    valueExpr: string(result) + " days"
    colorExpr: '"blue"'
