---
metrics:
  - name: cluster_node_count
    query: count(kube_node_info)
    suffix: " nodes"
    colors:
      - color: "green"
        min: 3
        max: 99
      - color: "orange"
        min: 0
        max: 2

  - name: cluster_pod_count
    query: count(kube_pod_info)
    suffix: " pods"
    colors:
      - color: "blue"
        min: 0
        max: 9999

  - name: cluster_cpu_usage
    query: >-
      sum(1 - rate(node_cpu_seconds_total{mode="idle"}[5m])) /
      count(node_cpu_seconds_total{mode="idle"}) * 100
    rounding: 1
    suffix: "%"
    colors:
      - color: "green"
        min: 0
        max: 60
      - color: "orange"
        min: 60
        max: 85
      - color: "red"
        min: 85
        max: 100

  - name: cluster_memory_usage
    query: >-
      sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) /
      sum(node_memory_MemTotal_bytes) * 100
    rounding: 1
    suffix: "%"
    colors:
      - color: "green"
        min: 0
        max: 70
      - color: "orange"
        min: 70
        max: 90
      - color: "red"
        min: 90
        max: 100

  - name: cluster_age_days
    query: (time() - min(kube_node_created)) / 86400
    rounding: 0
    suffix: " days"
    colors:
      - color: "blue"
        min: 0
        max: 9999
