---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mloa
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mloa-secret
    creationPolicy: Owner
    template:
      data:
        DB_HOST: &dbHost "{{ .DB_HOST }}"
        DB_USER: &dbUser "{{ .DB_USER }}"
        DB_PASSWORD: &dbPassword "{{ .DB_PASSWORD }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        # db init
        INIT_POSTGRES_DBNAME: mloa
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: mloa
    - extract:
        key: cloudnative-pg
