---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mloa
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      mloa-backend:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.5
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: mloa-secret
        containers:
          app:
            image:
              repository: ghcr.io/phekno/mloa-backend
              tag: sha256:d8a23a9b31c0d0d122d51bf9b2492733dabcccf8b9816a0703ad08c6b9e17914
            env:
              PORT: &port 8080
            envFrom:
              - secretRef:
                  name: mloa-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: mloa-backend
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["{{ .Release.Name }}.phekno.io"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    # persistence:
    #   config:
    #     existingClaim: prowlarr
    #     # enabled: true
    #     # type: persistentVolumeClaim
    #     # storageClass: longhorn
    #     # size: 1Gi
    #     # accessMode: ReadWriteOnce
    #   tmp:
    #     type: emptyDir
