apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:yc3+uv2u6JqIgUKc4fNgKRy9niay,iv:AodSZkta496q+dqZsS1ZDK3i4tx+hau2fadbBCuQXMw=,tag:PUtbCIbPY+xgT6yUBLTKYw==,type:str]
    admin-user: ENC[AES256_GCM,data:JSfJRmc=,iv:8f3C8Ex1OZnYmafgB9eppA94CD91zQBD4Ene1JJB8Yk=,tag:RrBfGTTdMQoBcu3a+zGAmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaC81dDlEWjVHdjUwMEhU
            L1REc0ZPUnU4SU9hdDBuUjdZVEZqZXU2TkVFClVRVGh6eTlJZ3pwQ2JBdlRqcm1X
            L2FSVlFMU3loOXljOVMvR3psamdVek0KLS0tIHFkWTI3dW9HQmMvOFNtL3IxdzU1
            cFFyMlE1Rjl4TlhqQmNwVjNMclZsSzAKwjd+1Y7knb3UAMAO3WRAkF8QylrzABvM
            jRA4tscVh0vixIRnYwy8nmfrKjk9vD6mDNUGGbMdKNrYlR26l/z3gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T05:54:14Z"
    mac: ENC[AES256_GCM,data:ePZ6l58ScK14nakABFZeyyijqia32WKNmaCs1A8KH0r2YCx2V+5kEMaVzSGR6AsAHN0+6WVSaMrWsuyr37vCmgwmYHCU6KrFLzcLuhFrcqEmWPwrRWkjYT28+xQuHMu5UY+FTMowZt4tmAa9sXpBunik0iLV3k+/6Dh0qZwRTl4=,iv:XNtMS77AkPXKdA2xjbTia5MzUjBtuyjwVP9KeSr2+Uk=,tag:8Ep+ccK8VsYBWLtFAqQzhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
