apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:i8m3J2anNSM7yJMuxAJnwIDcSL6BqaqjTmZCflG4C9VmnYBrVACXvQ==,iv:/76v1zwdG8oPY2fH2bewQKFmYpcJSi8re8kitqTp+XI=,tag:4FbpmZuCJ2Jinm78gwBu6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVVNiUXZaRGRybHU2Vkt2
            MTVYendTYmJXZTVYYVVKQlRFM0gwcHRBaG5rCktOb3VYVlJuTnZNU1NkbzlkOU1K
            TThWalI1VEt6TUNyRDZKc0FGRlZUWncKLS0tIGxDT004Mk90b244TnhOUCthNDlR
            SWlaaHVNZzZWNzViTzBieVhCQTdwMGsKLubH2ZaeYsQj1fcH4ksBgi/+QubOjPY8
            MB1lVs2LkxQzELhd0H5agjfazf0CBw2W0WYAp8y2F8MjJvYo3tdEGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T15:33:04Z"
    mac: ENC[AES256_GCM,data:KtyXQLp4xviiMVIAKuiducnbYNo3a2iclERWiKtJgS2Ie4URiE/CdC+sE9UGwgOBuVqsL/ku/+ObcOWx/lMNTbcdZzcGDNqJsROyI3hTobAwctt1empDHEtlZuzrlfEWQ/D2Yq6j4yl0tO/OmR7K9776Y7TXJTPQ/hBzZ+xN2WI=,iv:qVy8wY00EE1hjRzmALEP79gte+/QbhBBlFbEOSelb+Y=,tag:61yz+Q4dNptn+CKlvYXIaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
