apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:svHiok4IbJgumZU5IF7bduX0zVRznEqN00ypHapa8GOMGLjjyCxC7w==,iv:vfOLkNMsTNiqabo3fLpKMYUoysjvlF1ILnm4zb3kE64=,tag:cUYBfVnBbU+j6PEoKY1A8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybG9naDdpcGtHOGplcnlD
            R0dUdFlDN3lJUmVyS0lvelZ4TE9aRGN0L0VFCmd4U0R1dS9MYnlCb3I5K0owSE9n
            bFUrOGVkNnVpV1E0RmV1V0JnRFZjUVEKLS0tIENkOVAwcTR0ek9Wazd0aE1memhO
            Unc4T3YyTjdzY2dJTzRocUhVdnlSclkK3gMffwjOmgq/bp8uDaYup3qn4V20tn1l
            BPViDOnfQOVWPuA4ONcFHB3hxyHRD7RsZxi1pjcVgb+75hfueze2wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T17:27:14Z"
    mac: ENC[AES256_GCM,data:n0PqG6RfB52RCqYhBr1PMUCbiRSQSSF/9Hep6nZDOUuc5kogc/hGyBnnEc3Czp3PpjPv+L0XEdg2xzyhJXD/nsiR4puNNXh9lExkzmkQ7ifFon/oejcdGiGnpaY8wMmCD9poxgwaLh1Sx6MLrJpTF4s+mgRmINxG0oehKHyAYN0=,iv:3nAUe8oTYDCWN82ayOB+EDg6rVLAMfBBFN+P+BenozA=,tag:FT5ZM8gIsq/eWuy68XGqKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
