apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Qgwg21lI5tApIu7sOKO+6ySEpCmcehCzweOaQD/juLgyW75AIBA1XQ==,iv:+2RpXLLPQVHY0iOfYaoy+WLeIFaYkPwU906eRbv1/Xk=,tag:QAq3XxqRC9HLb3e+wVLnWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Z2lrWHEza3NkUDRFeTdZ
            TnNJT3VlTDNHVlJ4QWFWeDlYZGdjWHBXNlN3CjhhMms3V3V5dXJWaytsc0YvaG9G
            YTN3emlUU3NhNCtUdGxLU0ZIVmpDdlEKLS0tIHEyR1hRYmhLZVFlNDVROUVEbjk2
            MklraE9sUTBSMmJ5OVU4ekloZFpNelkKiYm6IFxOgjdrgcCsqWvBxB5pEntsDCls
            jMYTW1C+RJwIr9qOUEuSiAMh8cszV13twqBJl1RaQJ6KfsALFwuP4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T16:19:48Z"
    mac: ENC[AES256_GCM,data:VRnMvHLoK/A4jXKTCYQjqDDsjmWefnP7uDMrn9RVC06VRqsYP2HUpE3iA3oKjbaSBILXGYAK/yZ8DpwFx/VFjVBOjK+wWDNTwj42oyoNyK6SPrkOBS3oMvOsaRZQiFoiif0ql2SuFJDpZul4q6Yly0C7ZYg1PIkBw9P5E7TvZH0=,iv:mTNRLxs/Qkq5RWswx+qnGaCz/Q2fPgk83/NrZOgecSQ=,tag:FABcXUMlk9jwKuOIgYbM/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
