apiVersion: v1
kind: Secret
metadata:
    name: onepassword-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:jZ//BQf0fqUDx4gbOF/BVGLbtGHCvGjjijruaf0tWvu9RBBCMKNUAubUNz4N8dkiMBEpCFJ2n3ENaNwUoy1nkCEQAvbGwG+JvR9xkY0gxgKrzbGuMLEQHTQvyrtnTXJ/wbl88gvcyKBErRLcYpVgJqShexAI2y1KjL4zLxrpBJBS7M7WcNXa0HyLihSDGZkeHxhC5mDXGjg3wBe3rb3ZrHs6QI37UKQZLGPBjHh/AyXPPh7bnTBGV9B6jYHY9XAJseY0UZR21wSLTeQBPWHiCyIc5c+1ckwHH7Y6gO9cnb8TT0jjPmCQe5N34Tuvwl/mCRNH4WUd9UYtpit1YqJzVpS3GvRPTktyyeUPBDr1yXt85RDNpIdmPMax7MVfEZ6GGTmtk9hO2rI6ltjkkVARnz6V9sAypRtGz8WYcigy3xSBJzMifyxu/aX+eI+gDRCzlhtqiyS8rCno4OYeFPBvr+oOPhWcJwHxGjzHbdCyqUELkcXeMbubEQ7x7fcs1nR+tufS62fzmdDpVh3zZ7JYPAW8MzfujIDuwEWmiqq3MyDJbOHFc6OlsmLRWHjvdQgAUC2MNX//Xywj2TcW3YxBDjpY38ZcLmCF5/NQye29+lH3XyisseStg/HP2+JVdhJHHSP2yGEJRwPib0Iv8/nYWEjfw+jBpXcnghS1GY7s8vUuoHjWJhhZzmeMprKS4mtI/aVSMqbruC8Yp13kPn0Eb87jijwY5ehkwYmtksCaRsMIyWRXlQIMPLGnVAQ/S8q1B3zlFUrhI6VlnXi2AOScluGsraQcqOhw/tbEN95EL8OjDanTapLAzIJbaoGsAan5iELYkIXOd9s5iOt+fmZjzxk4ubjngr07oFqSpGx+bwXp+SRSK+/XCKJ0ySGGwDbbj3SPqRlYh3cu92ArFa3YvlUDZga9JbMbrNa4lz0FN4wKejlSLHkAimmISzm1TUFeGC/XHdmbK0eDiwmcG9W2I9GroIaBqcivkBo7LsN5tkFFDNpXftUjfbZmZ0qNmzFT9FAqI6m0qYLwAYj7GGvPMqTJPw8L5feNEePWd+JQbdhvhZuzw4FA60W8xv8ZjSNS1FheDhNmahRvwLVap0T/WD2h8RTUyOYkOYuUzQX1eRk=,iv:qvbQbG67TwIRtQZy0945GrWVlIufmjfOu1lR9V60nNY=,tag:blSiNz4iJSd+UCph0GooAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18p353vdvr8n8rlm7xn24qpff5r7c8s0688jyw7hlcxg04r9aq5lqlz0qm2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERVVWSXN3STIwcDNlMkFN
            emlKWEFkdmxKZlg3bHJtTnY0WTRsVGlrMUNjClJla1pycVphOC8wYlNxbzcxL0Vk
            UVVoVUg3RCtRUDlLRmh5b2RlVWg2WGcKLS0tIGQwdnErSUZhYXc2Ry9aMGFOQjBW
            SlQ4cFAzQktVbjN3alp4WmFMMjVVTFUK3xYuvYNzdm41m5UDg12XDC5FMNWC9YeF
            BbMkYr+3Olgvf4Cocl3jt+84/sR1aYlelBqo/W/WcjQZzjUZbktTIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-03T01:49:33Z"
    mac: ENC[AES256_GCM,data:feijlXCAuQbn0cyB1FlxlQARpiH7iz1kFNti99GQSoFOhv1RQNooSM8vUheTcMJIIHikuESlRDkUdN1ij+jjpfiDL4Zs/nsXJKtscNbsqYRER0mSgAggvpA6kZX5aOBAWJMHqNHC824y/frvxGCj0p2LKHtCFBhpY2bfqqkwzKY=,iv:rl02XignfhjozBQzc7gZfBVj1DNJBIV5qr23ud0rm20=,tag:9tqcclqzNGfUG/t8JqWSzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.1
