apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-secret
stringData:
  onepassword-credentials.json: ENC[AES256_GCM,data:IQpM6hZ33G5XqQ6L6NY+ORjzcdcKwBpV6SOKROzWesmCZZV7lPqYls4PMh7NLB9MC5VJ7Pfmj37QVAOkKpzCt+dxEmNLkG5sZciH1DYYAf9fkkkd/lBWv2nElpRiF3x15Mww93z8dj0Lgg05aAEresXOIazEja3HJ3h4Rf8TqqDLjXa9ZrtEg1O0x/aaQzOl7sYjbGdOXAHJLW1eba0LgC8KZUImzfqMTr9X9APFrQPiZmnLSDYG0AiDfPIv8Swt1zrJ5ZdVODbC6NV4jWAR4a4FJpppbzqF/gQne74ndaeGeOFOdY3DwGirS1gkN1dMVAPPvVcLG/UFNj9cZBptJEXMsgSK39O8rX5Tpg09KSkXjw8XdK24jc9VWrGRJXqMEaLX+b1vPHzbNBIMOCT5AuUYUKfB9eEHPuwnqj7ThuE3LhNnkTl8/7CvXIy/eFt8HRjM6gTCJ6fWl1qLcPZEXi85v1zt3mbPw3ZGbxfZyOjjEzVxjh6f4R13AvzgATLJy9UBgwaIENKJCJXygCuDYblUyjQa5A94Ip18FHDGBJA2anD0leX1zguTtn1r2wDJqdsqoW0ksi3WyLRfMeNkqlYAsmncNlyWOCIP978QteNqWw599+7moTV8iumzPWXE8wHPqc3uWaiotn2PJnUlGPzWP4wkWt7mJy29PqpAYZjxk+kImZ1mxKMplkbxu1JfmufK9ZZnuhJGYra37qD7XQcXpGdLTf86hdK6q46NRLWQr7k/sm8hdVg9YbSM+fHydCY22rbeJSR59SjGsAgjjRIFxFZ8WLMwZ3PPd+REZBF5I49aqotVonJU76pW/CUH4O6NeGCX+dxCFEmPgnOGLNmWhXVA++SU335W/g9HuSV4KPSH6c+BeQpknaUKCJjw686mWDEfsvlBYbUF7iDVo7XW0ftqNpdrRKxQrLjHCq2oDelN4MkYKl33WcuI0Gl7UOg9/+CQUAIS2Gc8MkpJOULDO0ImjUQq4YJ+vgUxkFQ+WVgnM6Be4aoU2GxwLH4ZZuUi9SsslCPi3msIqEVLfoyjIxEns+OC5Djx99HtQTkF0u+IgyJwRXpNRzJHmODcgDyGEVxxMop8ogKEZykc2YHxXGBMrRDhiPjPO+tHkWprkB6Fxnp6F+u6dEb+Jr1yq0Pa0zKVkeiWrP4+K6gg3doN7/ajLm1+9yAraoQ4F3etH6tzzXaVua+9RgIhABJ+jj4iFLGFqayw0XAGl61KTR5pIkMnNk71OW12chk+TKOkZjF/otZ/NjDGbhg1jac9qxJbzlO9lYB7H6+Kx2Amabkv61ywjDGKTPJ2L24/DKAiao2LKq8ltbL0HsezuUhdcT2oVWq0YIlFja0wpGmqzzUX1nDBodxpmpXgpmiyYLvFzZOH2wVgBB81+Za/d3Vg5ny0jSVgfG6AFqqxpWk06wtShdlyg+1ZLRp10/H5QwAPQL0XgkdMeeIzcgEhBuUKWp9y4SXaWKMVl3fPJ2h6eaSz9hcjiOXBMD02uE4VmJEPhXAKqecrV1wl6798/gFXcvBG6GnA4//8Y/C/EMd2J9xnubKplDriOzVepedBmvAKGeD/NDcgfZYSigUpA+DYYALw8Za7Phi2Aev2tLZuvfSDIcqZdGwxtq+wXSZLY89Cg0DyI/fDfd7OgVXDKvd1tWVG+uOFS4rnUoWU2mHFcsbt3v/qC3TY0huSVpa1+g5w6RivXvx04KI7nJ48R813hofwjybBE8lPPUNMREWW2gbSmUjAAScthJODtwplycBdtCR9rfPSdtDMgu7exaYuDoVE+wGWckksOSz3VED+b2Lv6x6gjQyuCJCeODg9pBHNzmKTsB9HkceiHmpzhwtbg+nL1kbDey7izlLn8vTFW4o4yLdw/Q4bsrBYj7zaJpHujzYfFo/mnXVyE5+ho88rRs3G7rEzrFmc+akh,iv:nPFjQteBFVp8r0iRDZlTMTEGUDg6GlATyNYvLCpy25U=,tag:i9aMjJ1Or0zHAvzPn8AmRA==,type:str]
sops:
  age:
    - recipient: age18p353vdvr8n8rlm7xn24qpff5r7c8s0688jyw7hlcxg04r9aq5lqlz0qm2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCS2NvNVovaURrQmIwaEVX
        NVdaNU1lb0hqb1Q1c25ENDVmQ1BsZUhEVWwwCjdVZ2V4OERRaUp1cUFzemx0bElX
        TzRBakdraDNZOVJwblhPZWVwYmpFc2sKLS0tIHdGNVc5Z3VoUUNCc3pvR0l3YmY4
        Y0Joanplem1RZmNFTHJFd29IckxQRkEK5pIQ3AgnSIt0jfZNP1DVbS9z3ZYZO+nD
        UUcdWNafIG96VnqR6kyowvtO2IYJMWmK0JHKnLlXzC8mUQtHnsRbGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-10T00:45:50Z"
  mac: ENC[AES256_GCM,data:sI/GaM/iIpLRSzuMFV3bTuFUK7F0hxSY/FIJwSToVaBosS4wkE+zMCtEujsO7Y5nurDiGSiSRaoaFYpDHvatoILKCq0T/Knfg6/NjveVgh+zbXhS3KcTYOx9vwO0NdFpDCKTdEzSk9RBs757tjDuG33QWJPXUafrjrICP4qABjM=,iv:HNHMnZCmX1Yv1E5qyJLr8ilNN65YSdBXRJdb7WI3diQ=,tag:gTnCccN3hXIZQb7s93Pwrg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.1
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
stringData:
  token: ENC[AES256_GCM,data:45hO9RixDju5obtp4R0jDXsFV+GeeH1bdzDnvgMEOx4a+e238/GZyU8VQcny7rC3svcZwHZNogL1YQPOW3AQBGuN+zfRsRlNqcnQCo2KqphdcFFbWsst+2iKYfP7JFy/e8bAwCIjx2hCEfwXaSOsibRNTwp3ce+7RWGRIKBL5GuaRIW5qgn2KGLN6n6UPGE7aHv0M/2o+3aBY6gGRNAt+1Hy9onuVmfr70+SX4CKFtVOxo8LighFJXvXBFmC4PS/2Ew5gU8Gv9wSiapa10kemduouz7p41H+ca6H4UlRfjRbCCNDsiGUOmH6YZTJfWPJazyOd7il04km+Cj3KohGNXt/JNJsGNGGfrdHl4t57jX+NMXIPtIr0SovFV8iG/WLO5TfLCyKoC6bbQnM1Ho/fgvkZI2hxo583VDxc5KS1RvrITQoL8wVdzQLu+YA9wNB66Fpxep6sBEAyta/VKL7bzy1sPlOQmD7ORWGw6WOon0svWiUcYQfULGPn531MxBUyNBH2NZdtz1rRvqQOd9M7pwyXmdfytf5XtsYBNKZhj7EMyGCyrj3X7LJkLSw83Ijb3vmB8ft0MjpmffNJkR2KzrBat3uPdej/mweoXN0X1zvnj8zG8/5WUR8eGYlVBUbSojTFIMWlsxCj7quarkkCk6tAzDdXdYL+x5q8L36pYkkwltdHJfe66n3MHmMItbThydPpGL4GTj2/3bc3CSNwuHr3XQCX3hAbOC4q5ckSIxKhaIau5hyMNNrhrz7UsWw6o9pqUpHN/1z91+9q6gd/ty2Ykpk6Zz00Dhnc7fc2bJICO+YfgBQqYo+VR9c3tsReWMeyWh85TmrvVOm4Y24HX+J,iv:+4vu7B/Ld8Bc6Y0A4hsFrTyLPH7/eTzXzyTIWlnxPkU=,tag:GNxlzeu5wnpcZ+jcGymHOA==,type:str]
sops:
  age:
    - recipient: age18p353vdvr8n8rlm7xn24qpff5r7c8s0688jyw7hlcxg04r9aq5lqlz0qm2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCS2NvNVovaURrQmIwaEVX
        NVdaNU1lb0hqb1Q1c25ENDVmQ1BsZUhEVWwwCjdVZ2V4OERRaUp1cUFzemx0bElX
        TzRBakdraDNZOVJwblhPZWVwYmpFc2sKLS0tIHdGNVc5Z3VoUUNCc3pvR0l3YmY4
        Y0Joanplem1RZmNFTHJFd29IckxQRkEK5pIQ3AgnSIt0jfZNP1DVbS9z3ZYZO+nD
        UUcdWNafIG96VnqR6kyowvtO2IYJMWmK0JHKnLlXzC8mUQtHnsRbGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-10T00:45:50Z"
  mac: ENC[AES256_GCM,data:sI/GaM/iIpLRSzuMFV3bTuFUK7F0hxSY/FIJwSToVaBosS4wkE+zMCtEujsO7Y5nurDiGSiSRaoaFYpDHvatoILKCq0T/Knfg6/NjveVgh+zbXhS3KcTYOx9vwO0NdFpDCKTdEzSk9RBs757tjDuG33QWJPXUafrjrICP4qABjM=,iv:HNHMnZCmX1Yv1E5qyJLr8ilNN65YSdBXRJdb7WI3diQ=,tag:gTnCccN3hXIZQb7s93Pwrg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.1
