apiVersion: v1
kind: Secret
metadata:
  name: onepassword-secret
  namespace: external-secrets
stringData:
  1password-credentials.json: ENC[AES256_GCM,data:BYvHN/zvcdkYHM9jvJJdOnrThChR0gO9auSWO3KEekcyK0PhzLFXDo6692oEa4AOoRSsN820xvq9sl7ChlKHA7B02FWxJqxbNP6ox7gmp2aRVfSLrZwoJAnM007t/sIxQB5n/pdJy80cb/GkANBXiGN1YiAWOsaEOv5Ajge9jzHHHzCBFR8z6W2ugEjpfW2HZTVRP1aYuPzEfsUkjiJyQQCxOkCMYls+mUhMrOKkvwpDJGFEmQ0tCJlngkhOlQDiVynv/9q06oYTUb1m43u84BxPOyylQ5QTqn/zuq4T6cUjVantSagajt4N8ZITcXRFgV7NYei9PHDAHDbzEXtkOHmOIPjcRnzbrHqmVRwHlp3fsahiVri7oxkxoki9FWIdG/RIak47fUI8/UuGx7tM5b6ExuUdRCMYVxmDvXCEq9VUHc5Dy5+a8ah4WEURBE4j3q0zLtOTTNJiJIKpBCLSMHkiooMAotA21ogGX0BosKYjx5fuAWPNUXlAvgt8ffweMlE+C9iQUEyP7jiySfcer6s8WV5UT3lCeQLhneqU+5vqbJprqn9/UGz3hACZdfM+LcnQgUH7SOb3ACn2DU26KgPlwtFsN+LnYIZz0xqTuS75imP+CEktQsrCowhMOduJ3glP0qN0S0elogD0T/0LNOBtIYDOAANpX1lZpQ4L+zwuvWPX/bucTDGqcmz27rvnxe8+evWRxSQl0JoU9ghIu0q+LaFvI8jRPsHPhJropJRXv7S2XfC2fM0U0R5xDnmKmN8Ul7qG9DkDOedojl4UMDTiR5iY9QGO8kw3+H/T/PKbNrLtw/QeHQkQZMMCqALW39RpmWDTqsJx9sFVu4PuUMIFwpI/f3/09vRItNuB69KUGgIArXa8LsJsTDLKJhLIsPnq/85ycFuG6fAJCwvVhfnIAexKqgi29yCa47OtQPC54Y0Ub5SfK7eUinGoEQQueWONdPZFd/7OSAvT1tIPMaSlPa6seKnI16r6ZhJ0Sar3TkQbiPgyHe+3n9MV1i1zDugWsjpx1hDOxpoAZ2MaL3qWjkSV3WCg5tkRVNvpVGisFexWnHDahy7xCbpJjXQMOrICAlMrzyC8720/1hDic/XS85dCXeCQSUrRty2TABcRXVgrR7Vvd8X/kZ/uVUDGzFv+56mn7FelR+GtU2iRlLmYtvyZr5BxRYlXaamaZsyHGhnJpHTVqK7hyxXB0RTrCvMgk5paXPncJbH7Xw+9xzOdqrGQ4emryI3GXVEmqI+xGjiDUzBndrAj62vCUS3XX6EJCQ1Q3etjkfRx3HEATChPHykKlPS7jvybpghFlJxHJ4o14iTFB6zlLuoKaNYSGg3CRTtbMs878E2+7PBx/U7jgs5nwdMFyBhgCIVzTe7hYVwhCXbt9t2lqXG1ZFeb3cIC0HlxCz+ojwxXyeZGCE0orUOeO33TbTOZ9BZChg==,iv:SZSVeXif67U+ZMUHpu2+HB/g3QSBTUftdyxb//gll1s=,tag:0ZjWe+QHBRU8t88QEYdjKg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCS2NvNVovaURrQmIwaEVX
        NVdaNU1lb0hqb1Q1c25ENDVmQ1BsZUhEVWwwCjdVZ2V4OERRaUp1cUFzemx0bElX
        TzRBakdraDNZOVJwblhPZWVwYmpFc2sKLS0tIHdGNVc5Z3VoUUNCc3pvR0l3YmY4
        Y0Joanplem1RZmNFTHJFd29IckxQRkEK5pIQ3AgnSIt0jfZNP1DVbS9z3ZYZO+nD
        UUcdWNafIG96VnqR6kyowvtO2IYJMWmK0JHKnLlXzC8mUQtHnsRbGw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age18p353vdvr8n8rlm7xn24qpff5r7c8s0688jyw7hlcxg04r9aq5lqlz0qm2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T15:05:46Z"
  mac: ENC[AES256_GCM,data:VmJJM4TYIcGYAS97xbSLUGFI6eQvhs6njxSLBYQC0UdHS47z3ppfDjkiFpufUFcZgNaqQhqsC5e2Tk+4jaU3bbmkrlUQ1Lf9tPQ1MIqw8GLQo5jSl7UERom6Mfr4rpyq+C3E9VGxp1C4hkIM40lMJun6hrZt7okUBee617fN800=,iv:B12rGcdPbWlG/SAeDJqTr8TYkS8xhMBVHsjRoo/opIk=,tag:EM2IBzpV9/UjcVgED/4pMQ==,type:str]
  mac_only_encrypted: true
  version: 3.10.1
