---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: prowlarr-secret
    creationPolicy: Owner
    template:
      data:
        PROWLARR__API_KEY: "{{ .PROWLARR__API_KEY }}"
  dataFrom:
    - extract:
        key: prowlarr
