---
exclude:
  platforms:
    - "ps3-disc-keys"
    - "psx-bios"
  roms:
    single_file:
      extensions: []
      names: []
    multi_file:
      names: []
      parts:
        names: []
        extensions: []
filesystem: {}
