---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-restic
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sabnzbd-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .BUCKET_NAME }}/sabnzbd"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: sabnzbd
spec:
  trigger:
    manual: restore-once
  restic:
    repository: sabnzbd-restic-secret
    cacheStorageClassName: longhorn
    destinationPVC: sabnzbd-config
    copyMethod: Direct
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

