---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
components:
  - ../../components/common
  - ../../components/repos/app-template
  - ../../components/repos/onepassword-connect
resources: []
  # Flux-Kustomizations
  # - ./onepassword/ks.yaml
  # - ./external-secrets/ks.yaml
