---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      engineVersion: v2
      data:
        bucket: "{{ .bucket }}"
        access_key: "{{ .access_key }}"
        secret_key: "{{ .secret_key }}"
        region: "{{ .region }}"
        endpoint: "{{ .endpoint }}"
  dataFrom:
    - extract:
        key: loki