---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app recyclarr
  namespace: &namespace downloads
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: *namespace
  components: []
    # - ../../../../components/gatus/external
    # - ../../../../components/volsync
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    - name: longhorn
      namespace: longhorn-system
    - name: volsync
      namespace: volsync-system
  path: ./kubernetes/apps/downloads/recyclarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
