---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: radarr-secret
    creationPolicy: Owner
    template:
      data:
        # App
        RADARR__API_KEY: "{{ .RADARR__API_KEY }}"
  dataFrom:
    - extract:
        key: radarr
