# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.100.50.150:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.100.50.150"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-control-0"
    ipAddress: "10.100.50.100"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/6e17833398fc8f856d0ab60e80c1606e2fe60d628edae4b397592129ca6bf604
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:6d:e4:6f"
        dhcp: false
        addresses:
          - "10.100.50.100/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.100.50.1"
        mtu: 1500
        vip:
          ip: "10.100.50.150"
  - hostname: "k8s-control-1"
    ipAddress: "10.100.50.101"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/6e17833398fc8f856d0ab60e80c1606e2fe60d628edae4b397592129ca6bf604
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:23:76:0e"
        dhcp: false
        addresses:
          - "10.100.50.101/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.100.50.1"
        mtu: 1500
        vip:
          ip: "10.100.50.150"
  - hostname: "k8s-control-2"
    ipAddress: "10.100.50.102"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/6e17833398fc8f856d0ab60e80c1606e2fe60d628edae4b397592129ca6bf604
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:20:0b:e2"
        dhcp: false
        addresses:
          - "10.100.50.102/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.100.50.1"
        mtu: 1500
        vip:
          ip: "10.100.50.150"
  - hostname: "k8s-worker-0"
    ipAddress: "10.100.50.103"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/6e17833398fc8f856d0ab60e80c1606e2fe60d628edae4b397592129ca6bf604
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:ba:64:10"
        dhcp: false
        addresses:
          - "10.100.50.103/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.100.50.1"
        mtu: 1500
  - hostname: "k8s-worker-1"
    ipAddress: "10.100.50.104"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/6e17833398fc8f856d0ab60e80c1606e2fe60d628edae4b397592129ca6bf604
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:39:1e:49"
        dhcp: false
        addresses:
          - "10.100.50.104/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.100.50.1"
        mtu: 1500
  - hostname: "k8s-worker-2"
    ipAddress: "10.100.50.105"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/6e17833398fc8f856d0ab60e80c1606e2fe60d628edae4b397592129ca6bf604
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:1c:9d:74"
        dhcp: false
        addresses:
          - "10.100.50.105/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.100.50.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

worker:
  patches:
    - "@./patches/global/machine-disks.yaml"
