apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:lWrPKUGmbiLT,iv:v5c8l7HMPU7S5Lni1CE3+Vyz6yMJ+TsxBCpi4HUx5lo=,tag:Z9MwGelYY5Y6pbLhApBlEQ==,type:str]
    SECONDARY_DOMAIN: ENC[AES256_GCM,data:zr7Pm60FNQ1NqydutOb1HA==,iv:+eRLEeqz7Bc9Fu07vBs8j39AIMcpVnRhkmzYjEOhtRQ=,tag:z9XJNmKzdbSNH65YPTSVbA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:z6/BaRkU+qmXgeInP3ZPcg==,iv:eIOJUnKTmjNLH9DwG8MeQtJn7eEyeXGG67y7YzQFEh0=,tag:Mo1IllyeCX9Ka3uYjkcw3w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:YX6oXZVW7wUddEUwDJXJB8DVfL6OOCEhpNcEBC7Mrq1gw4Rc,iv:qX/ijePulaJBo04cWurZacPcdSaQeZwZ2jCI752UlU0=,tag:VSFIVb7e7+GkZuNS1bTBgg==,type:str]
    SVC_K8S_GATEWAY: ENC[AES256_GCM,data:gBInh+XxyTC8jRL7Yg==,iv:aGTT4x47VL3X6ON/aOzxh+SnXTNAPeXvZfylqqWa1V4=,tag:tsCBTbOc9L3UVeZDxIO8Sw==,type:str]
    SVC_EXTERNAL_INGRESS: ENC[AES256_GCM,data:4v5O+h8FoqUG0QByuQ==,iv:UkVMfw0iPw9gEYNBILPEfW6q7OxOJYXEPb55y5QSTV0=,tag:xqut5aNQFiu/KYSr+JqXnw==,type:str]
    SVC_INTERNAL_INGRESS: ENC[AES256_GCM,data:o8hPhv7HrTVo+Z86jA==,iv:0Hzas65PFx2EqmfMd17TUjxMi5WseoAik+csUBZ1/Nc=,tag:PFahK/Tkre0r7+8BP2SF/g==,type:str]
    SVC_POSTGRES_ADDR: ENC[AES256_GCM,data:re4lBGyErGe8rBonUg==,iv:yGDUcQOqUBCQ7aDzXJjU5lyEerarTBlfz+j1AO8tzz0=,tag:seRpyYgC4AkYHYxZ0wIycA==,type:str]
    SVC_VECTOR_AGGREGATOR: ENC[AES256_GCM,data:et2b50xAArgQayh9EQ==,iv:aHqmwPIlhQL4JER7Mf4ANTCMOdAAt8OYnY4/ZHTYpc0=,tag:/oAeGOOFqLCwxC4Z+kJ+9A==,type:str]
    SVC_MINECRAFT_ADDR: ENC[AES256_GCM,data:RjjhKo3q86WMsebqww==,iv:+GqtyEK9oI766DY9tXFWWTSPXzDHi9yLf7xfNCXRft0=,tag:jxZ3ZtJ6QKj4jZpKRsOu4g==,type:str]
    SVC_ONEBLOCK_ADDR: ENC[AES256_GCM,data:pKCoCjzARkBtpSpTlw==,iv:WKNJzc0F6edUqihgfsnpBKL4qN/axwgHFCIrekyxQaE=,tag:x0u3qmi3vCsJeEt71BtNfw==,type:str]
    SVC_QBITTORRENT_ADDR: ENC[AES256_GCM,data:IvLa5+Q7U2S8Tn/4CQ==,iv:waDwNNcTuIexLRQPxzamAj9aQZtNou1tiiMr8mC41gY=,tag:WdlMW8zhUAT+y2kL9xFqDw==,type:str]
    SVC_MOSQUITTO_ADDR: ENC[AES256_GCM,data:3jE/SFAegXx23RMdpw==,iv:wt+bDd7KX2QG4p1WC1vezC/rCGGnirTNp7ON6xUionA=,tag:idTNwQXggcKAMGCpY3BfyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUM3Jkc1o0Nmx5bGFrQnJa
            dHBTYmRaTU5JTDZ4SVFwUVhTQitDSEVqeFNVCkU2d09ZNlB0WVR0dWx4dllKdDJr
            WUR1VDNvd0JtTFZ2NFQ2emZjTmpXYm8KLS0tIGdxbUJQSklQZk1UK2RUWXViT3Bi
            L1FQYnh4Sk1acXVyZW02ZTRlbmRGa1UKCckz8UQIFtQESxc5400xPH1IOjTLA1uC
            2eMrhmLEevD3vyGBmwIXlyaXjWSCXBMAaLOHjnjLJcVzaQ4vGNGRTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T00:34:38Z"
    mac: ENC[AES256_GCM,data:g+nNt6TZhr6aYPMcSjoXFtBaj33+PAgPHpeXhkL2osoWJLLBlsNzZTmkjaUq6buDold23k76HJetc7WrjultoGroZn6Z+57U31rLVv/m9N4akxV06wP6C8Q8DDpI496mCsniun926JMDEFQw2g2Q0wA0xzl1u33PrH6/d8mjpOs=,iv:unkOlIcyxfvqxzckIvJjsEJ3gUGSJM4QFLWzenPEgFw=,tag:FStDktqfvO+E9pujqKcIYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
