apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:ka5JpyGy6UX8jYnzfkEmVYQO2tMtPRQfAQd7dyGVjfmqWYXo2aQCi/Dnc3KXu9KRgtHaT0zhPsPcvfmDCj+xv3RUps/X5GzcG/GCk99euZrDBDbISU2XbMq4aGph+A==,iv:fuB7N8VS6cB61yfbBKBKDEU04EUFLuyjwXS6MPKcLUc=,tag:U30Sk+82IB2tE/Lj0+1NUw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:y09YyHx1JfhU,iv:x5bcnOgAjp+6Fq1Uj8HCWxHmb8tl2et7BHnmZ0ksJfw=,tag:xDtjU7uWoXnzR+qKUYwG7g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:hcIK4s9TeHW2oF9siJ8Img==,iv:qAd8jT4YZj/sHA55gRgF3WdT+WKlHHGU61kfwem+52I=,tag:umexfZaLG60VuhzakSwJmQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:k6bakqvoRF8WCKc0aJNDVO2Xjdb+PptopY+7bcvF9FJ3Q19b,iv:U2vh/ECFZ+Lxuh/MBexd5cNDK5dqHnrIh6VKueeFKD8=,tag:o4yKVeAnitSjbHQYPXt4uQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWkVVaHEzd1A4STc4RlpP
            V3gyRXdhQ01SM1YwRmpkM2JzQlk4dDlnSWlVCk0xZFhzbFNtUzVuV1NKdEIrMTlm
            OGhvMjhyVmZiUWtyZFcxRzRoUXNrT0EKLS0tIDRtb0ViQy9ybnBvQk1HS0RpdVZU
            ZzNkeEF1VVl6WmJKVnQ3UFVmeXp3OW8KpXLOt4EJusNqJV2w5orYmkt/gnjZ3lHg
            3QRamsG3KaqR8/jhlZErYCFY1wjcZZtKEdnO5/b+ROLXk3dshnupag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T17:27:14Z"
    mac: ENC[AES256_GCM,data:UGCbVPg/Yij83YH9KwVWhzMZ7hdQKYMiW73Y24U3ypv6nhUdk6zMp+P/2tAErQ206Ur7gprOHvbHocdVwWvOcHN0LR72VZP3CrphhdeQM8ubu2iCMJ3W4nUAlouvt95C/fFHCE9VUql5wmLrF8Y5Pywmx4ZmtcqflaClsYkOSGg=,iv:mvEboItDYKhX1HSNX4GRjzU4e7a7feSShBKi9dUDJU0=,tag:HSUnUMPD9ndPu4HvaxpQRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
