apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:waM/KlFHf47Cl3raU+OkRElyufirTe5eVipo+afrHwLzejZhbkGF1HU/Ng/WrbGdNpgjv7TRhaPbnoIk5Dqo5lB1meGApsE1tvU63w0sTny6bGrg38O2kI2XCyZGWg==,iv:KZevl+I1osV6mKDg0/t/Q5xBLZMcXz4inkyudgs5wBE=,tag:twqcOCQtipi0Wm9Hc9C0mA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:BuNjFHsWBxGg,iv:0FDyYfhKKXlW7O0MdoOig23WBWPd/sIO4j1bvZRzLq8=,tag:zP3uDBkv40DyxcMoQ3HOqw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:djBXl7lcsOg3GU21uCgakg==,iv:tZhp1cZgf0yYVreJsJS5cGusr2q9DJXzsWikheGIomg=,tag:xjRRQkwu1rVpQdgLQQsrqA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:0tgzvMcmjTnWWFSJqG1R9MFWlGgGBB+DIXEJOsAoxAweCfS4,iv:qfweyhB6uXBed/pPdzXQ4EPuhDX8JajULBtxvRI8/mk=,tag:Su2SR7S3Wp9vYzPpHRtKhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabURwNGozSlJxbzJLcXB0
            TnBnWTR6NHdrL05qR0VHRkpYME0xeGQ1NUZRCkJJU0ZFcUpkUDUrVmtqZitMSWRE
            c21KWEl2cmkwWnNncS9YV1FuM29qVW8KLS0tIDFzN3N3WHdwRlN4YlJFQlpxVHVJ
            NFB4VGRrSGVabkZrYlluRjgxaHNRbkUKfvZlqGMvmnrhWkPQiJWuJ072jrWmj3yF
            FGF3wdj70pYsm369HZl3r4HmJ9TE8cWYVDeDd4Z1lIPQN5t+NlXRtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T15:43:40Z"
    mac: ENC[AES256_GCM,data:1XEa+6X8uI5rWxVmDhW66NIPU0K4kgEAjxUvAWpUPL3C7ExbgojJQX2fqXCOSKz1mx2VOCpzbJYpoJ74z6S/uXk7S8k4psWmssa5boW/jn0CPjNndoT9ME6i45lNpZeoOYBr5hLUFn0/uOSCOLmg88GXtL6HBMG+6BKRbNHCIQY=,iv:88wUxMimRptL08h5rfDQpj4mR2kjBOXQVDdvQ4ZTcuc=,tag:ZJkhaQH7NGvOPZnkFUccXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
