---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-restore-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  claimRef:
    namespace: media
    name: plex-config
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: plex-config-restore
    volumeAttributes:
      staleReplicaTimeout: "30"
