---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db
resources:
  - ./cloudnative-pg/ks.yaml
  - ./dragonfly/ks.yaml
  - ./pgadmin/ks.yaml
components:
  - ../../components/common
  - ../../components/repos/app-template
  # - ../../components/flux/alerts
