---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-survival-datadir
  labels:
    recurring-job-group.longhorn.io/daily-backup: enabled
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
