---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: nfs
  superuserSecret:
    name: cloudnative-pg-secret
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 7d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://phekno-home-k8s-pg/
      serverName: &currentCluster postgres-v1
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: aws-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: aws-secret-access-key
  # Note: needed when recovering from an existing cnpg cluster
  bootstrap:
    recovery:
      source: postgres-v1
  externalClusters:
    - name: postgres-v1
      barmanObjectStore:
        destinationPath: s3://phekno-home-k8s-pg/postgres-v1
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: aws-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: aws-secret-access-key
        wal:
          maxParallel: 8
