---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pgadmin
  namespace: &namespace db
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components: []
    # - ../../../../components/gatus/external
    # - ../../../../components/volsync
  targetNamespace: *namespace
  path: ./kubernetes/apps/db/pgadmin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
