---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snmp-exporter
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: snmp-exporter-secret
    template:
      data:
        snmp.yml: |
          auths:
            cyberpower_v3:
              version: 3
              security_level: authPriv
              username: "{{ .SNMP_USERNAME }}"
              password: "{{ .AUTH_PASSWORD }}"
              auth_protocol: "{{ .AUTH_PROTOCOL }}"
              priv_protocol: "{{ .PRIVACY_PROTOCOL }}"
              priv_password: "{{ .PRIVACY_PASSWORD }}"
  dataFrom:
    - extract:
        key: ups
