apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:EKDMTL4+0fyRfo2Oil4TAjoZMASYIB2hGsGqk8n54u7nnhEZ3liMGA==,iv:ALyjcB8lvfgwT7a8y/X3AySoJREcTQKxCjA12bJm064=,tag:j5VwVDnq15DWLllbMERhvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU1EyZHBRSzE0cjdjNlIw
            TVMvQ0xDb0Vvck01cmMxOUZCWkpYeExqczJVCmdUY3IrNURQOEZHcDcrZG5LSkxW
            b21QKzJhbHZCTXhPUndKT1NGNERhV2sKLS0tIGFIVDlzckViTlI1ZnBBLzVvV2lH
            bDZpdVY0UVlLbkVQNVdWS2w4WlFvQ0EKchpygk9NK3lxs4bjcdnY1Vp0W3zbKuAJ
            Ss+6CxEIHv4mDQCzDnsTM2+WwvdrpyjqSu6M4Xj9soaopnNPPjsi4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T15:33:04Z"
    mac: ENC[AES256_GCM,data:m5z6OvkFN6dZsTZOn3O8pgXVQ4xy4T9YsWJY+Abnzth1R/odIL2iuO+5933nXwLn4KmqqXyD7cI5PUm+hR+rctCZSlOlY+KUpgayCvbDgff137nzKtTwQvDuMbgC79gwEn/L9cU/nniycnpCl+sfhKG363zVPrG2Il1Ev4OU4Mc=,iv:WR3fOa7Tu2QAITtn9HhOUzyOrGZDeJhI0bs0TTGWBGE=,tag:lruh5GhRwu52CCyQXC2teA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
