apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:kK9QLlBW7i5uQnss7p4J5471M1hppXfMGxPrLhrTttu7BiwEdyip8Q==,iv:WxiMl9N2Qz5UX5txxHNI52C4GJMuAatESrHRdTdHlV8=,tag:cvP8eYEuotI31h9qICLx8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVVFQQkkxeWxPR2d4eWV5
            emNqRks0dnMzTmQ5V2tKTWF3M3hORENFT0ZVClQwamlrdmJxMytnS0RWWWZNenVn
            eG0rR1p3ZjhHL1hRbS9vRnROcGI5N1EKLS0tIDhKZU5jcTRic2w4TENpL1dzVHps
            azNJUnRVOFBSOVBoTURWeE5takxJQU0KuNzZTriSVzGAWx75sdbe8uSPpCX326Ug
            dkrSLPxU7G+fSgoWfoGM7PVeZbNeqnAH/C29BDHgwEdSMkYy1Z/Wzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T16:19:47Z"
    mac: ENC[AES256_GCM,data:PXywTTsb19EueJ+R+GHHqcm5xql8k573haseUhWauuDAaJ7Kb/elCQaLYQ6OJgO/zwnL0l3sMWyjKvZ8h4/2fxh8OZIx/pM0alwNQotjMPB5VYxzEaj9qwqwxlwF6UHEztn78+oFaW8rZInlXNCtUpp6bWhK1kjajTPfSGLdROE=,iv:zgcJCFlJkF2e+MyFLGEj59sjc8mHtuKxHhXjiUUgDeI=,tag:JCdimyUPAHIxLmhoXifUOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
