apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:eYQr0mM80xwcwTGwN1UUmEIN9nYQf6O3LYVwtaYvuB7RkU+951F2Lw==,iv:BWz3TM0NH6Tje7WSFzu/lJJPITu4wxToWcqdhVwdhh8=,tag:AzMcu3ESXTgXUBpjmuzHvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAza0EvMW5XOEVxWEZFZjFx
            M1RBUSttSlVnMTFielRmWk9vRG9Cd1A2M2dFCkt1bm1lbmx5eHRNbXJ3eURHWXFK
            RVUrUkh0MExCdFhGc045c0F4V3pEMGMKLS0tIGRWdjNCQzBZbUx0Z2dUNStNNUVl
            YXBvMXpWSmR1ZXA1REZsYW84enhaY3cKTzL0+pFiY5sHYN1UMFSEdfaentW6HPbY
            y1+Am+nApY+H+C5H5oyU1pfwOeCJWmdjQcxyMBB8L/6HDTgwJS8Dfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T18:52:27Z"
    mac: ENC[AES256_GCM,data:qZv6+lcm290sNNhjSls4cr0ql/8PDP/SXVO2KkzcYh15IMp39MQs4UUc1jj3xQt3nbGFRZTHB2Tn8yD+iaXKMix1suLCzU470Gv/oUhk/uw9F+/GtXMywTLGyVHOaykFu3v3CT5GIQBsPmSJr4TrNNyE2mNZfGPXwAG5kIEDk5E=,iv:SDmQ33euQoFtdCkcGi1naJiMO1zVgipC2Z93btYGe0Q=,tag:BFd5J3Gu4QoDLY5krbs+1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
