---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ebay-watcher
  namespace: utilities
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ebay-watcher
    creationPolicy: Owner
    template:
      data:
        # App
        EBAY_CLIENT_ID: "{{ .client_id }}"
        EBAY_CLIENT_SECRET: "{{ .client_secret }}"
        DISCORD_WEBHOOK_URL: "{{ .discord_webhook_url }}"
        # Database
        DATABASE_URL: |-
          postgres://{{ .postgres_user }}:{{ .postgres_password }}@postgres-rw.db.svc.cluster.local/{{ .postgres_db }}?sslmode=disable
        # Postgres Init
        INIT_POSTGRES_DBNAME: "{{ .postgres_db }}"
        INIT_POSTGRES_HOST: "postgres-rw.db.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .postgres_user }}"
        INIT_POSTGRES_PASS: "{{ .postgres_password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: ebay-watcher
    - extract:
        key: cloudnative-pg
