---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ebay-watcher
  namespace: utilities
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ebay-watcher
    creationPolicy: Owner
  data:
    - secretKey: EBAY_CLIENT_ID
      remoteRef:
        key: ebay-watcher
        property: client_id
    - secretKey: EBAY_CLIENT_SECRET
      remoteRef:
        key: ebay-watcher
        property: client_secret
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: ebay-watcher
        property: discord_webhook_url
