---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homeassistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      homeassistant:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.6.3@sha256:6f6b427121f376c92dac2ce14b99ff088010da3f082142fd8b86b4ade563328f
            env:
              HOME_ASSISTANT_EXTERNAL_URL: https://hass.phekno.io
              HOME_ASSISTANT_PURGE_KEEP_DAYS: 30
              HOME_ASSISTANT_USE_X_FORWARDED_FOR: "true"
              HOME_ASSISTANT_TRUSTED_PROXIES: 10.0.0.0/8
              HOME_ASSISTANT_UNIT_SYSTEM: us_customary
              TZ: America/Chicago
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      # annotations:
      # k8s.v1.cni.cncf.io/networks: |
      #   [{
      #     "name": "multus-iot",
      #     "namespace": "networking",
      #     "ips": ["192.168.30.200/24"]
      #   }]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: *app
      tmpfs:
        type: emptyDir
        advancedMounts:
          homeassistant:
            app:
              - path: /config/.venv
                subPath: .venv
              - path: /config/logs
                subPath: logs
              - path: /config/tts
                subPath: tts
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.phekno.io"
          - hass.phekno.io
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
    service:
      app:
        ports:
          http:
            port: 8123
