apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:XG4KXwAfxlKsPkmJiithAwzwKGDuMruTuB3bY/tnP5LtV3F+lj8UEQ==,iv:P8J8ZbKt8rFEypSQE7II0ahzvx3iiHNaG6qOZEsU82I=,tag:XlegAVvG2X3g+fvk88TegQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdjlGcld5eFkvZmIvTEFV
            OHU3U3dIZ2hJeG93Mk14T2JGUnloYjVOWm5BClZNS0haOHJIZFF6cUthbnRLTnk4
            L0hCdG53Rkorc0xwTzh3VlZyVW5QbWMKLS0tIHFwb1RvWXRSZTVqYXEyUFJUVHlH
            QXFoajl3KzdNcjlYeEJ2VDkrdEo5Tk0K/pksYbd1pl0qRomV6DTVWRrMV6rGghp1
            mkQ4LLmbMR0WbVFikkmktQD6iqAI/8H89KR3cby2jU4MCFTAiPj48w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T18:52:27Z"
    mac: ENC[AES256_GCM,data:ZyKrycYDxjjWQ5FTJ7I+XyfClsc7EZtgTcgvgX5Z75915wUtHPh9zCQrkG/x67YMwd5KntOi5NsrtauMqJCyftuaws1WzxXmo0G1Az/MNNhY1iO1pRmD3yN82UAiGpGvrJZfz+T+aOHdciyPGGD4k9TKL4w2fmeO7ooEk9Ypnq4=,iv:Ol/nBEVCYiwZq7Bk2NyEONQU3vSym/MLd0V86UCylDA=,tag:ZrFjiEm8ng/+A2k0d7O19A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
