apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:CWZP5Vdrdr2cunOIkgyJAcQVxGLYprlet6bz7Ich84LQrYONUw+Afw==,iv:CCyxM66xfIYQKZrdZqj0kJbWE/WuaEI1uuLkbTUqgXw=,tag:VCfP8UZXG+EsyZYtsPTShg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRlk0d1FmVWRnS3JiRXBi
            RC82NldOQWVhNld6akREamhzeHJQdExUbmlNClJDNFJ0VGZGQXRrbm5KRDNCWlRp
            RkxJb0ZqTFJLSHp6c3FhSWFGdXZYT0kKLS0tIDdhNlVxeW14R1hWSWJlVnRFZ0xK
            LzA5NDVGVWZ2blBwS1ZheTZqd2dYNUUK3Rv4DdZIf1hTmd2xkydVAneuwPSRCj52
            9x6ssSjZB2rgJR3Yc5dI8zWFiipEv0npEB9DkC/N/Ur+PtY4oCq5Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T15:33:04Z"
    mac: ENC[AES256_GCM,data:u8Mt4nvx8dw0Gj1TTMltPTeQf0dAG1Oo1loK1v9aKVdLZGuHsJyI1qKSYKroXYbYQTxxooMRqG0DmI+wmCGDvopuJ20n2OhvFSTIvqlop3eBAq3ILZQ/dykfNtKwuPWJMBh76+vvyX+R5dcFzN3XAEIN26UeUBK4gTu5pREw3IQ=,iv:IL6vso5r1RezZfRSJ8vD54yOt4lG7SgBX+7dZe9IK8o=,tag:87iJmne5taKdpeDW3lVlog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
