apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:LQhwcvQ0V+3awNRV90tAw/SkxRsZ6LxPmbXjLI64lzXFup5lzW3VRg==,iv:vQDYaftkBEnD+A7V6GK/BNwJgt40nYskYiQcdxyDA6I=,tag:PP0LsdsVJ9LZOmT9TukIKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSXJBL3RCdUlmV0xaZDhE
            TllONkROdlcxTnFGeVF0VFdZTDUzYUF5T0M4CjI2SklzcVAwUUFRL2ZzaVN4R3VJ
            Z240dFhjSmhRcTFYU2FsUXN6Y3Vta0kKLS0tIGlMNXJyVGF2QStpMzhEVWJML28r
            bERqOWhtSVJTdGpZVmpQTnBXWVJmZXcKU8D2ic3baltVjMdYoYpb0fYbELwK6t/I
            zaHDovE/GudcM9V0EG7viEOYuIFFjDP50WW2w/WWaonIPqxFiSM2Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T15:43:40Z"
    mac: ENC[AES256_GCM,data:hQpDnHAD5V9YlBsFdT5ofI9OokwqlPD/6Gy4LjkAmD90pt/mKff/y74L8FE3s1wuqT9tCMYFacC0du+Y5yrGQwHaklHA4IBoae+o4yeqTEKfl0UwGX65qlhvHHXl6BMtLXzU7CqvP2cDgOLR4VreB6/ttPNv0eeTzYgi1H0zzxM=,iv:CviC5Ac0JfErTXGrC73rmvyH7OmwIjIci6VQS1ya9bQ=,tag:zTp0O6y9TodTJYdl5z4i2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
