---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-server-gatus-ep
  namespace: network
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: echo-server-internal
        group: internal
        url: https://echo-server-internal.phekno.io
        interval: 1m
        client:
          dns-resolver: tcp://10.100.50.2:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
      - name: echo-server-external
        group: external
        url: https://echo-server-external.phekno.io
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
